apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: thuhavothi2001/restaurantapi-app:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_HOSTNAME
              value: postgres-service.default
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              value: '150101'
            - name: POSTGRES_DB
              value: restaurant
            - name: POSTGRES_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: flask-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


